### ISSUE TITLE
SplashScreen tag name does not match entry in Windows 10 Manifest file on some devices

### ISSUE THREAD

**Issue by tibersept** [apache/cordova-windows#322]
The Windows 10 Manifest uses the _uap_ namespace for UAP/UWP tags. The following tag name for UWP in _confighelper.js_ does not match the _SplashScreen_ tag in that manifest, a modified _uap:SplashScreen_ tag name does.

https://github.com/apache/cordova-windows/blob/8cc627b8f5fb4a0959c4ef7a5994a4f358215fd6/template/www/cordova.js#L848

https://github.com/apache/cordova-windows/blob/8cc627b8f5fb4a0959c4ef7a5994a4f358215fd6/cordova-js-src/confighelper.js#L28

Results in _undefined_ access when retrieving splash screen image path etc. which causes a bunch of other issues ...

Don't know what the reason behind the differing behavior is, maybe the Windows 10 build version. Version 10.0.17736 requires the _uap_ namespace, version 10.0.17134 is only ok without the namespace, same app build.

**Comment by wifisher** [comment]
Same issue here. Breaks reading of the splashscreen preferences from the config.xml file.

A simple try/catch block in confighelper.js would get it working again:

`function Manifest(text) {
    XmlFile.apply(this, arguments);
   try {
        this.splashScreen = this.loadTags(splashScreenTagName)[0];
   }
   catch(e) {
        if(isWin10UWP) {
           this.splashScreen = this.loadTags("uap:" + splashScreenTagName)[0];
        } else {
           throw e;
        }
   }
}`

**Comment by janpio** [comment]
Hey @wifisher and @tibersept, thanks for your reports here. Let me check if I got everything correct:

Depending on what Windows 10 SDK is used to build (e.g. `10.0.17736` vs `10.0.17134`) the `splashScreenTagName` that can be used to read the splashscreen from `config.xml` changes from `SplashScreen` to `uap:SplashScreen`. Correct?

**Comment by goffioul** [comment]
The `uap:` prefix is part of the manifest template:
https://github.com/apache/cordova-windows/blob/master/template/package.windows10.appxmanifest

Given that the above file was modified more than 3 years ago, the real question is did that work before? And if yes, what else has changed that make it not work anymore?

**Comment by janpio** [comment]
Hey @tibersept and @wifisher - I am still interested in recreating this problem and then trying to fix it: What steps would one take on a new Cordova app created with cordova create, cordova platform add windows to be able to reproduce this?

With a local reproduction I can look at what is actually going on, then further debug (or confirm your observations what code could fix it how) and possibly fix it.

But I need your help.

**Comment by wifisher** [comment]
It's been a while since I looked at this and am currently away from my office. I think that all you need is to add the splashscreen plugin and then include a splashscreen preference (like the background color) in config.xml. 

You see an exception in the console output of VS and the preferences don't get applied. 

If you look at the Windows manifest file, you can see that the tags do not have the uap prefix.

**Comment by janpio** [comment]
Ok, so I tried to recreate this:

```
cordova create cordovaWindowsSplashscreen
cd cordovaWindowsSplashscreen
cordova platform add https://github.com/apache/cordova-windows
cordova plugin add cordova-plugin-splashscreen@5.0.3 # explicit version to get around this bug: https://github.com/apache/cordova-lib/issues/790
cordova run windows
```

--- 

This lead me to see that a splashscreen images during fadeout is always missing, which I created an issue for: https://github.com/apache/cordova-windows/issues/357 This also includes the following output, which might be related to what we are investigating here:
```
'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
Exception was thrown at line 944, column 5 in ms-appx-web://io.cordova.hellocordova/www/cordova.js
0x800a138f - JavaScript runtime error: Unable to get property 'attributes' of undefined or null reference
```

Is this what we are talking about here?

--- 

I then tried to add a red background color as suggested by @wifisher:

```
	<platform name="windows">
        <preference name="SplashScreenBackgroundColor" value="red" />
    </platform>
```

This worked just fine and switched the background color to red. What am I doing wrong @wifisher?

---

So back to this issue here, looking at the suggested fixes for a problem that I can't reproduce for now: https://github.com/apache/cordova-windows/issues/322#issue-405201688 https://github.com/apache/cordova-windows/issues/322#issuecomment-481292910 https://github.com/apache/cordova-windows/issues/322#issuecomment-481296222 All of them basically make the script read from  `uap:SplashScreen` instead of just `SplashScreen`.

But when I look at that code, the only code that is actually _reading_ from the resulting object is `Manifest.prototype.getSplashScreenImagePath` - or am I missing something?

---

Went on to test other preferences for the splash:

```
		<preference name="SplashScreenDelay" value="10000" />
        <preference name="FadeSplashScreenDuration" value="5000" />
```

And indeed, only when it reads from `uap:SplashScreen` these work. But the code used to read from them doesn't really use `uap:SplashScreen` in any way - this is just a side effect of the code crashing earlier!?

Am I looking at the right stuff here?

---

What is also confusing me:

> Version 10.0.17736 requires the _uap_ namespace, version 10.0.17134 is only ok without the namespace, same app build.

What does this mean @tibersept? I can't put this in context to what I am looking at here. The manifest has been `uap:SplashScreen` for ages as mentioned in https://github.com/apache/cordova-windows/issues/322#issuecomment-495371401, so I don't understand how "version 10.0.17134 is only ok without the namespace" could be.

**Comment by janpio** [comment]
Ok, https://github.com/apache/cordova-windows/issues/357 now has a fix and is completely unrelated to this problem here.

So I now think this issue is actually about this:
![image](https://user-images.githubusercontent.com/183673/61219473-986d5f80-a714-11e9-87b3-3c6c7d51c58a.png)

Changing the tag it tries to read from `SplashScreen` to `uap:SplashScreen` does indeed fix the issue properly it seems. I don't see any possible problems by this change and created https://github.com/apache/cordova-windows/pull/358

@wifisher Any objection on fixing this here instead of making the reads less brittle?
@tibersept Please see the last question in my previous comment - that is the only aspect I don't understand here yet.

**Comment by wifisher** [comment]
@janpio were you waiting on me for anything? I would like to see this fix rolled out so that I can disable the hook I have been using to effectively do what #358 does.

**Comment by janpio** [comment]
Not active in this project any more right now, sorry.
