### ISSUE TITLE
Cordova platform add windows@^7.0.0 command not copying the node_modules

### ISSUE THREAD

**Issue by aman2604** [apache/cordova-windows#325]
**Cordova platform add windows@^7.0.0 command not copying the node_modules into node_modules\cordova-windows\node_modules **

Instead all the node_modules are present directly inside \node_modules.

Might be the side effect of https://github.com/apache/cordova-windows/pull/317

**Comment by aman2604** [comment]
@review - @erisu

**Comment by erisu** [comment]
@aman2604 This is not a side effect and expected behavior.

Node modules are no longer bundled in any of the platforms including `cordova-windows`.  

This is not a side effect of PR #317. This PR only copies the node_modules folder if it is present. Since node modules does not exist, there is nothing  to copy. The use case where the node_module folder exist is from stand alone non-CLI usage.

For more information, you can check out:
- https://github.com/apache/cordova/issues/32
- https://github.com/apache/cordova/issues/6
