### ISSUE TITLE
Deprecate support for Windows pre-10

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-windows#361]
I think we should deprecate Windows pre-10 support and remove it from an upcoming release, as @janpio already proposed in PR #264.

@janpio what do you think?

**Comment by janpio** [comment]
Makes sense, but is a lot of work as removing the Win8.1 parts destroys quite a lot of the code and makes it even less readable. #264 stalled because of that.

**Comment by brodybits** [comment]
Thanks @janpio. I would like to take another look at this as I think we do not want to support 8.1 any longer than absolutely needed.

I am interested in cleaning up Windows 10 support as it is still needed by a major client.

**Comment by janpio** [comment]
Sounds good. If I could invest the time to tackle this, I would first get rid of everything obvious connected to Win8.1 and Phone, then see what is left and how it could be rewritten in a simplified manner - especially the MSBuild selection is absolute crap right now.

**Comment by janpio** [comment]
An interesting thing to decide is if VS15 should still be supported or if we drop everything but VS2017. Since VS17 Microsoft includes a `vswhere` executable at a known location that can be used to find the `MSBuild` location, which would make all the VS/MSBuild detection logic we have (reading registry, trying paths, bla) obsolete. This is our #1 source of problems right now.

Also, do we maybe also drop Windows Phone 10? It is EOL and unsupported by Microsoft as far as I know.

**Comment by janpio** [comment]
I just went through the changes of https://github.com/apache/cordova-windows/pull/264 and I think most of them still make sense - it becomes clear which parameters can be removed, what warnings should be added, and quite a lot of the code and tests that can be removed. What the PR didn't cover was the cleanup phase and a sane MSBuild detection mechanism. But otherwise I am pretty happy how good it holds up, could definitely be a good idea base for starting a new branch to tackle this properly again.

**Comment by erisu** [comment]
I just want to point out that  `vswhere` actually was bundled with `VS2017 version 15.2`. It didn't  actually come with 15.0, the initial release of VS2017.

During a recent setup of a Windows VM, last week, my VS2017 did not have `vswhere`. It either bugged out during the setup, hence I didn't have `vswhere`, or it installed and older version such as 15.0. I ran an update later with the VS installer and it fixed everything.

**Comment by janpio** [comment]
+1 on just including it (if possible) - would make stuff so much more stable.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
