### ISSUE TITLE
Error: WebGL not supported

### ISSUE THREAD

**Issue by ankitp5** [apache/cordova-windows#383]
i am trying to load the 3D using the babylonJs but not able to load it ends with error

**Uncaught (in promise): Error: WebGL not supported.**

the same thing working fine with Android and IOS platform.
after searching i came to know webview is using Internet explorer for rendering the contents.
so is there any way to change default Browser to Edge at time of Creating APPX?
how can we load WebGL in ionic Hybrid application?
ionic info is below:

Ionic:

   Ionic CLI                     : 6.10.1 
   Ionic Framework               : @ionic/angular 5.3.1
   @angular-devkit/build-angular : 0.803.29
   @angular-devkit/schematics    : 8.1.3
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.3.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0, windows 7.0.1
   Cordova Plugins   : not available

Utility:

   cordova-res : not installed
   native-run  : 1.0.0

System:

   Android SDK Tools : 26.1.1 
   NodeJS            : v12.18.2 
   npm               : 6.14.5
   OS                : Windows 10
 
i already tried by disable IE and then create build it won't work 
any suggestion or Help 

thanks,

**Comment by breautek** [comment]
> after searching i came to know webview is using Internet explorer for rendering the contents.
so is there any way to change default Browser to Edge at time of Creating APPX?

Both IE11, and pre-chromium edge only supports webgl under the `experimental-webgl` context, instead of the `webgl` context. I'm not sure if it's possible to switch webviews (not familiar with windows development whatsoever), but even if you could, you will still most likely run into the same issue for users who haven't updated yet. Of course this will be less likely as time goes on.

A better solution is to perhaps fallback to `experimental-webgl` if `webgl` is not supported.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
